apiVersion: v1
kind: Pod
metadata:
  name: myapp-main
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', 'cd file && echo "This is temp data" > data && sleep 1000']
    volumeMounts:
    - name: file
      mountPath: "/file"
  restartPolicy: OnFailure
  volumes: 
  - name: file
    emptyDir: {}

