apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    description: Keeps track of changes in the application image
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  generation: 1
  labels:
    app: cakephp-mysql-persistent
    template: cakephp-mysql-persistent
  name: cakephp-mysql-persistent
  selfLink: /apis/image.openshift.io/v1/namespaces/q8/imagestreams/cakephp-mysql-persistent
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: 172.30.1.1:5000/cakephp-mysql-persistent
